### PR TITLE
 CMake: update to eigenpy 2.7.10

### PR DESCRIPTION
**Pull request by nim65s**
This will have to wait for eigenpy 2.7.10 to be available everywhere before the CI can succeed.

### CODE REVIEW

**Comment by nim65s** [comment]
I thought we had to wait for eigenpy 2.7.10 being available in apt, but actually just restarting the ROS jobs did the work.

**Comment by wxmerkt** [comment]
> just restarting the ROS jobs did the work.

Because in the meantime the release to the buildfarm happened and now 2.7.10 is available on staging (but not release yet until the sync - so unless users have ros-testing instead of ros-main they won't get 2.7.10 just yet)

**Comment by wxmerkt** [comment]
Can we have a release tagged with this update please?

**Comment by jcarpent** [comment]
I'm doing that now ;)

**Pull request merged**
