### PR TITLE
[CMake] export target hpp-fcl

### PR DESCRIPTION
**Pull request by jmirabel**

### CODE REVIEW

**Comment by jmirabel** [comment]
I triggered a build on the build farm: https://gepgitlab.laas.fr/humanoid-path-planner/hpp-fcl/pipelines/6873

**Comment by nim65s** [comment]
The buildfarm doesn't know yet that this package has python bindings, so they will not be tested for now. You can ask me to fix this if necessary.

**Comment by jmirabel** [comment]
> The buildfarm doesn't know yet that this package has python bindings, so they will not be tested for now. You can ask me to fix this if necessary.

Not necessary as of today. My main concern is the finding and usage of the dependencies.

**Comment by jmirabel** [comment]
All CI passed. This is ready for a release.
@nim65s can you take care of this ?

**Comment by nim65s** [comment]
Perfect :)
I guess we can go for v1.2.0, or is there any non-backward-compatible changes that I missed ?

**Comment by jmirabel** [comment]
A few, but I believe they are either not important or they concern an almost never used function.

Old API of `Transform3f`
- `inverse` does an in-place inversion (modifies the object)

New API  of `Transform3f`
- `inverseInPlace` does an in-place inversion (modifies the object)
- `inverse` returns the inverse of the object, without modifying the object (i.e. it is const)

Some functions were moved into namespace `hpp::fcl::internal` to make a clear distinction between what is the stable API.

**Comment by nim65s** [comment]
Ok, this will do, thanks :)

**Comment by jcarpent** [comment]
@nim65s Do you have some timings for the release. I can handle it if you want, together with Pinocchio and EigenPy. Is it OK for you?

**Comment by nim65s** [comment]
The source release is already done, I'll push it here soon.

**Comment by jcarpent** [comment]
Could you push it now? I need them to update all the conda-force and brew instances. I will do the release of Pinocchio after this step done.

**Comment by nim65s** [comment]
done :)

**Comment by jcarpent** [comment]
Thanks.

**Pull request merged**
