### PR TITLE
[CMake] Boost::chrono in required for tests

### PR DESCRIPTION
**Pull request by nim65s**
fix build for Debian Jessie

### CODE REVIEW

**Comment by jmirabel** [comment]
@jcarpent Travis on Mac fails to compile eigenpy with the following error (from https://travis-ci.org/humanoid-path-planner/hpp-fcl/jobs/620257457?utm_medium=notification&utm_source=github_status) :
```
-- Found PythonLibs: /usr/local/opt/python@2/Frameworks/Python.framework/Versions/2.7/lib (found version "2.7.17") 

-- PythonLibrary hint: 

-- PythonLibraries: /usr/local/opt/python@2/Frameworks/Python.framework/Versions/2.7/lib

-- PythonLibraryDirs: /usr/local/opt/python@2/Frameworks/Python.framework/Versions/2.7

-- PythonLibVersionString: 2.7.17

-- Python site lib: lib/python2.7/site-packages

-- checking for numpy

CMake Error at cmake/python.cmake:416 (MESSAGE):

  Failed to detect numpy

Call Stack (most recent call first):

  CMakeLists.txt:64 (FIND_NUMPY)

-- Configuring incomplete, errors occurred!

See also "/tmp/eigenpy-20191203-86911-vhhe9h/eigenpy-1.6.8/build/CMakeFiles/CMakeOutput.log".

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):

  https://github.com/gepetto/homebrew-gepetto/issues

```

Any idea of what is going on ?

**Comment by jcarpent** [comment]
Brew have changed the Formula for numpy to only install it for Python3. I will provide a new formula to fix it this morning.

**Comment by jcarpent** [comment]
It is down now. I will relaunch the test.

**Comment by jmirabel** [comment]
> Brew have changed the Formula for numpy to only install it for Python3.

Thanks for handling it. I am also fine with switching to Python 3 on Travis, if it helps.

**Comment by jmirabel** [comment]
Thank you.

**Pull request merged**
