### PR TITLE
Box-Plane collision incorrect contact point

### PR DESCRIPTION
**Pull request by Kotochleb**
When contact occurs between Box and Plane primitives, the contact point is incorrect. The same scenario, but with Box and Halfspace returns the correct contact point.

The images below show what the problem is. The green box is a primitive box imported from the URDF and the pink sphere is only visual showing the contact point with a plane at [0, 0, 0] with norm [0, 0, 1].

For the Halfspace as said, the location of the contact point is reasonable:

Box-Halfspace on the edge             |  Box-Halfspace on the tip
:-------------------------:|:-------------------------:
halfspace_edge | halfspace_tip

While for the Plane this point lies in a semi-random place:

Box-Plane on the edge             |  Box-Plane on the tip
:-------------------------:|:-------------------------:
plane_edge | plane_tip

Screenshots were made in Mescat with Pinocchio compiled with HPP-FCL version 2.3.6, but the changes in the PR apply to the newest version.

This PR fixes this issue and adds unit tests to ensure the correctness of the fix.
I also for convenience, made one of the functions in the testing utilis a part of its interface.

### CODE REVIEW

**Comment by jcarpent** [comment]
Thanks @Kotochleb for this PR which seems very complete.
Before moving forward, we have the plan to move soon to hppfcl3x, which is the next major release of hpp-fcl with major new features.
With @lmontaut, we think this issue has been solved on hppfcl3x.
 Could you check that this is the case by running your test on this branch?
 
 Thanks in advance,
 Best,
 
 Justin

**Comment by Kotochleb** [comment]
@jcarpent I did run the tests on hppfcl3x branch and the only failing ones were those related to changed positions of the of contact points and closest points in case shapes intersect. Values in the failed tests seem to be all right and match with what might be expected in the new approach of computing them. The issue with the incorrect placement is resolved in version 3x, and tests to check if the collision is in the right place passed.

If you decide not to merge it and move on with version 3x I will not mind.

**Comment by jcarpent** [comment]
@Kotochleb Could you integrate your extended tests into hppfcl3x?
They are useful I think.

**Comment by Kotochleb** [comment]
Sure thing. I am closing this PR and I will open a new one to the `hppflc3x` branch somewhere this week.

**Pull request closed without merging**
