### PR TITLE
Remove GJKSolverType + code cleaning.

### PR DESCRIPTION
**Pull request by jmirabel**

### CODE REVIEW

**Comment by jmirabel** [comment]
There is still one thing I am working on that I would like to push. Afterwards, yes, a new release is a good idea.

**Comment by jmirabel** [comment]
This PR also add documentation of the security_margin and break_distance parameters. Hopefully, the documentation is clear.

Note that the documentation explains what the code *should do*, although some pairs of primitives may not do that.

**Comment by jcarpent** [comment]
Are you done? Can we merge it before releasing?

**Comment by jmirabel** [comment]
@jcarpent Go ahead if you need it.

**Comment by jcarpent** [comment]
Which release number 1.2.3 or 1.3.0?

**Pull request merged**
