### PR TITLE
Patch release 1.8.1

### PR DESCRIPTION
**Pull request by wxmerkt**
Ports #255 to master to create a patch release 1.8.1 prior to the C++11/FCL 2.0 push

### CODE REVIEW

**Review by jcarpent — APPROVED** [review]
Thanks a lot @wxmerkt. this seems fine to me.
The next stage will consist in rebasing the devel on top of the new master branch.

**Comment by wxmerkt** [comment]
>  The next stage will consist in rebasing the devel on top of the new master branch.

This would require a force-push of the devel branch though, which can break history of people actively working on branches (mostly you I'd guess?) - would we want to do this rebase?

**Comment by jmirabel** [comment]
I also think merging is a better option.

**Comment by jcarpent** [comment]
I'm preparing the release.

**Pull request merged**
