### PR TITLE
[Python] Update bindings with requirements from Pinocchio.

### PR DESCRIPTION
**Pull request by jmirabel**

### CODE REVIEW

**Comment by jmirabel** [comment]
Solves another point of #92

**Comment by gabrielebndn** [comment]
Since I see you have exposed `std::vector<Contact>`, I think we should expose `std::vector` for the other classes too.

**Comment by jmirabel** [comment]
I exposed it because it is used by class CollisionResult. The other vectors are not used. I have nothing against adding them here.
I am just not sure where they fit best: in hpp-fcl or in pinocchio ?

**Comment by gabrielebndn** [comment]
> I exposed it because it is used by class CollisionResult. The other vectors are not used. I have nothing against adding them here.
> I am just not sure where they fit best: in hpp-fcl or in pinocchio ?

I am referring to the ones which are already exposed in Pinocchio. Since they are an hpp-fcl-related thing, and there already is `StdVec_Contact` exposed in hpp-fcl, it seems reasonable to me to move them to hpp-fcl, for consistency. It is purely a design choice.

**Comment by jmirabel** [comment]
Travis still complains about the frontlist unit test.

**Pull request merged**
