### PR TITLE
Improve GJK implementation + OBB overlap test + bug fixes

### PR DESCRIPTION
**Pull request by jmirabel**
This improves the overall performances of hpp-fcl in several ways:

- GJK should be about 30% faster.
- Closest points from GJK should be more robust to parallel faces.
- OBB overlap method should be about 25% faster.
- Provide non-recursive implementation of BVH traversal. At this time, I cannot say whether it is faster.
- For package managers, make usage of Assimp private (no more preprocessor variable).
- Some minor improvements overall.

@florent-lamiraux Could you validate commit 12e5357 ?

### CODE REVIEW

**Comment by nim65s** [comment]
Hi, 

I tried to run this on [Gitlab CI](https://gepgitlab.laas.fr/gsaurel/hpp-fcl/pipelines/5441).

On 18.04, I get the following compilation error:
```
An unexpected error occured.  The last 10 log lines are shown below.
…/test/obb.cpp:1358:10: error: 'cerr' is not a member of 'std'
``

And on 16.04, I get the following test error:
```
      Start  6: frontlist
 3/16 Test  #5: geometric_shapes .................***Failed    0.30 sec
Running 42 test cases...
p2 in cylinder = (-0.0295783 0.00332627   0.051201)
p1 in box = (  0.40428 -0.300945 0.0135652)
p2 in cylinder = (   0.433724 -0.00562366    0.443942)
p1 in box = ( -1.38168 -0.119498 -0.215351)
…/test/geometric_shapes.cpp(169): error in "shapeIntersection_cylindercylinder": check normal_equal failed
Disagreement between normal and expected_normal for GEOM_CYLINDER and GEOM_CYLINDER with 'built-in' solver.
tf1.quaternion: (0.318655 0.731568 0.478365 0.366653)
tf1.translation: 9.05036 9.21365 2.81701
tf2.quaternion: (0.318655 0.731568 0.478365 0.366653)
tf2.translation: 11.7577 18.4561 5.10981
normal: -0.239149  0.840828  0.485608
expected_normal: 0.273465 0.933585 0.231596
difference: 0.579568
tolerance: 0.01

*** 1 failure detected in test suite "FCL_GEOMETRIC_SHAPES"
```

**Comment by jmirabel** [comment]
For the unit-test error, yes, I know. As we are neither on devel nor master, I suggest to accept this failing unit-test.

At the moment, due to a subtle bug in GJK, the check that fails comes from an undefined behavior. A very small change of the inputs may result in great change on the output.

**Comment by nim65s** [comment]
As long as you are aware of it, it's fine for me :)

**Comment by jmirabel** [comment]
[CI worked](https://gepgitlab.laas.fr/humanoid-path-planner/hpp-fcl/pipelines/5442) as expected.

**Pull request merged**
