### PR TITLE
Remove QHULL from source installation

### PR DESCRIPTION
**Pull request by jcarpent**
Related to #333

### CODE REVIEW

**Review by nim65s — APPROVED** [review]

**Comment by jcarpent** [comment]
@nim65s Could you check the issue on the gitlab CI?

**Comment by nim65s** [comment]
We'll probably need a FindQhull.cmake

**Comment by nim65s** [comment]
Well, no, this won't provide Qhull:: targets. I'll be lazy and package a more recent version of qhull on robotpkg. Links are private anyway.

**Comment by jcarpent** [comment]
Seems reasonable indeed.

**Comment by wxmerkt** [comment]
>  I'll be lazy and package a more recent version of qhull on robotpkg

Are there issues with the system provided QHull on 20.04 and what happens if that custom qhull from robotpkg is not available? (E.g. the ROS buildfarm so far had no issues in building HPP-FCL - would there be issues now?)

**Comment by jcarpent** [comment]
We should simply provide a correct FindQhull.cmake to properly package the project. The reason is that this is not a good idea to internally package another largely used lib like qhull in hpp-fcl.

@nim65s Could we use something like: https://github.com/PointCloudLibrary/pcl/blob/master/cmake/Modules/FindQhull.cmake?

**Comment by nim65s** [comment]
Qhull has cmake exports since v8, and v8 is available from Debian 11 / Ubuntu 22.04.

You're right, packaging it on robotpkg wouldn't fix ROS use cases… But why did the CI succeed then ? Maybe it simply was never enabled ?

The FindQhull.cmake from pcl could be a nice solution indeed, until  we have qhull official cmake exports available everywhere.

**Comment by jcarpent** [comment]
@nim65s What is the status of the find helpers?

**Comment by wxmerkt** [comment]
We can test ROS-CI now so this PR is unblocked. Once it's merged, can we tag a new release as well please? Thank you :-)

**Comment by nim65s** [comment]
My latests commits are broken, I'll need to write another FindQhull.cmake first

**Comment by nim65s** [comment]
Actually, it looks like we need qhullcpp, which is available in QHull 8 (2020) on ubuntu 22.04, but not in QHull 7 (2015) on ubuntu 20.04. 

In other words, I don't think we can Remove QHULL from source installation unless we abandon Ubuntu 20.04 (and our Talos is still on Ubuntu 18.04…)

If nobody has a better option, I'll update the submodule and its use to QHull 8 and; and allow the use of a system qhull only if >= 8 is detected.

**Comment by jcarpent** [comment]
Sounds good to me. Thanks @nim65s for checking it further.

**Comment by nim65s** [comment]
1. Providing a recent Qhull submodule with the current strategy doesn't work, because we find ubuntu's `libqhull_r.so` v7, so we can't just build `libqhullcpp.a` v8.

2. Providing a recent Qhull submodule with `add_subdirectory()`doesn't work, because Qhull provides a `uninstall` CMake global targets which collides with ours from jrl-cmakemodule

3. Providing a recent Qhull via `FetchContent_Declare()` won't work on 18.04, because its default CMake is 3.10, and FetchContent is available since 3.11.

4. Providing a recent Qhull via `ExternalProject_add()` doesn't allow us to get the include directories at config time, so we can't specify those.

5. Providing a recent Qhull submodule to get include directories in the source tree + `ExternalProject_add()` with a local path as `GIT_REPOSITORY` provides everything we need, except `libqhull_r.so` is shared, so we would have to ship it with hpp-fcl binaries, which wouldn't be an excellent idea. 

6. I didn't manage to correctly link `libhpp-fcl.so` to the static version of that lib, `libqhullstatic_r.a`, because this would require everything linking to `libhpp-fcl.so` to be compiled with `-fPIC`, and that's not the case for eg. ubuntu's `libassimp.so`.

So I think we shouldn't do anything here. I also think that #333 is misleading, and that we can fix it without changing anything in this repo. If we really want to do something, 5 seems the only plausible solution, but we'll have to ensure that the `libqhull_r.so` we'll ship in our binaries won't interfere with anything. In that case would suggest to rename it to `libhpp-fcl-qhull-r.so` or something.

**Comment by jcarpent** [comment]
> If we really want to do something, 5 seems the only plausible solution, but we'll have to ensure that the `libqhull_r.so` we'll ship in our binaries won't interfere with anything. In that case would suggest to rename it to `libhpp-fcl-qhull-r.so` or something.

I think this is the best solution I would say. But requires some work.
What would be the work to be compliant with QHull 7 @jmirabel? Do you know which features are not present?

**Comment by jmirabel** [comment]
The issues @nim65s mention look very similar to the issues that lead me to include QHull into this repo.

**Comment by jmirabel** [comment]
For reference, QHull was integrated in https://github.com/humanoid-path-planner/hpp-fcl/pull/167 and the rationale of what I did is roughly explained in the PR.

I think we should:
- 18.04: not change the current behavior
- 20.04: I'm not sure. I haven't checked what the ubuntu repo provides
- 22.04: rely only on qhull from the official repo.

Is this feasible ?

**Comment by nim65s** [comment]
I agree. And for this, I think all we have to do is keep the repo in its current state.

**Comment by jcarpent** [comment]
I do agree with your conclusions. My only worry is that we have to cheap QHULL with hpp-fcl for certain OS, which is a bit weird IMHO.

**Pull request closed without merging**
