### PR TITLE
Add version utility methods

### PR DESCRIPTION
**Pull request by gabrielebndn**
1. Added methods `printVersion` and `checkVersionAtLeast`, analogously to Pinocchio
1. Exposed them in Python
1. Added attribute `__version__` to Python module

### CODE REVIEW

**Comment by nim65s** [comment]
This looks like https://github.com/loco-3d/crocoddyl/blob/master/include/crocoddyl/core/utils/version.hpp 

IMO, this should go to the CMake Submodule, and not in each and every package.

**Comment by nim65s** [comment]
Also, this prevent build in cases where the version computation fails, as

```
oss << CROCODDYL_MAJOR_VERSION << delimiter << CROCODDYL_MINOR_VERSION << delimiter << CROCODDYL_PATCH_VERSION;
```
becomes `oss <<  << delimiter <<  << delimiter << ;`, which is not valid.

**Comment by gabrielebndn** [comment]
> This looks like https://github.com/loco-3d/crocoddyl/blob/master/include/crocoddyl/core/utils/version.hpp
> 
> IMO, this should go to the CMake Submodule, and not in each and every package.

I copied it straight from Pinocchio and I guess the guys working on Crocoddyl did the same.
I do agree that this kind of boilerplate code is likely to be desirable in all of our packages and could well be put inside the cmake submodule.

**Comment by jmirabel** [comment]
> Also, this prevent build in cases where the version computation fails, as
> 
> ```
> oss << CROCODDYL_MAJOR_VERSION << delimiter << CROCODDYL_MINOR_VERSION << delimiter << CROCODDYL_PATCH_VERSION;
> ```
> 
> becomes `oss << << delimiter << << delimiter << ;`, which is not valid.

@gabrielebndn It may be good to enclose portion of the code which depends on those values between ifdefs. The else can be :
- a compilation error that explains clearly what's wrong
- a default version string,
- a exception.

**Comment by jcarpent** [comment]
I will correct it in the JRL cmake module for Pinocchio.

**Comment by jcarpent** [comment]
But, I do not think this should appear by default in the jrl-cmake

**Comment by gabrielebndn** [comment]
@nim65s, the main difficulty I see in putting this in the cmake module comes from the namespaces.

`printVersion` from Pinocchio needs to be in the `pinocchio` namespace.
The one from Crocoddyl needs to be in the `crocoddyl` namespace.
Hpp-FCL is more complicated, it needs to be in the nested namespace `hpp:fcl`.
The same can be said about `checkVersionAtLeast`.

Currently, files `config`, `deprecated` and `warning` only define macros and thus need do not be concerned with namespaces. If we introduce functions, all with the same names, we need them in order to avoid name clashes.

Thus, if we want to introduce support for this in the cmake submodule, we should either make it possible to set a custom (possibly nested) namespace in the CMakeLists.txt, or switch to appropriately-named macros, like `@LIBRARY_NAME@_CHECK_VERSION_AT_LEAST` or `@LIBRARY_NAME@_PRINT_VERSION`.

By the way, I see that a string macro called `@LIBRARY_NAME@_VERSION` is already computed and put in the `config` header. The main differences w.r.t. `printFunction` are
1. If the current commit does not correspond to a release tag, the commit number is added to `@LIBRARY_NAME@_VERSION`. If it the current state does not correspond to a commit, `-dirty` is added.
1. The macro does not allow choosing the delimiter

**Comment by gabrielebndn** [comment]
> Also, this prevent build in cases where the version computation fails, as
> 
> ```
> oss << CROCODDYL_MAJOR_VERSION << delimiter << CROCODDYL_MINOR_VERSION << delimiter << CROCODDYL_PATCH_VERSION;
> ```
> 
> becomes `oss << << delimiter << << delimiter << ;`, which is not valid.

Honestly, I do not understand. In which cases does the version computation fail?

**Comment by nim65s** [comment]
> Honestly, I do not understand. In which cases does the version computation fail?

eg. https://gepgitlab.laas.fr/loco-3d/crocoddyl/merge_requests/258

**Comment by gabrielebndn** [comment]
> > Honestly, I do not understand. In which cases does the version computation fail?
> 
> eg. https://gepgitlab.laas.fr/loco-3d/crocoddyl/merge_requests/258

Yes, that is why https://github.com/jrl-umi3218/jrl-cmakemodules/pull/258 was added. I thought this would solve the problem. Anyhow, I think it was fixed for good with https://github.com/jrl-umi3218/jrl-cmakemodules/pull/270, https://github.com/jrl-umi3218/jrl-cmakemodules/pull/271 and https://github.com/jrl-umi3218/jrl-cmakemodules/pull/273

**Comment by gabrielebndn** [comment]
Following recent discussions, I am closing this PR. I'll wait for https://github.com/jrl-umi3218/jrl-cmakemodules/pull/276 to merge in order to make a new one

**Pull request closed without merging**
