### PR TITLE
Configure and apply pre-commit

### PR DESCRIPTION
**Pull request by jcarpent**
Related to #279.

### CODE REVIEW

**Comment by nim65s** [comment]
While we're at it, I think we should also apply black to reformat python code, by adding this section to `.pre-commit-config.yaml`:
```yaml
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
```

**Comment by jmirabel** [comment]
I would like that people looking at `git blame` understand that they are looking at a code reformatting commit and not an actual change. To this end, I propose to
- to reword commit *pre-commit: init all* to something more explicit. Maybe *Reformat code to Google style*
- modify the author of the message to *(Reformat) Justin Carpentier*. I am asking because depending on how you configure `git blame`, you don't have the commit message right away.

**Comment by nim65s** [comment]
We can also exclude these reformating commits from git blame

**Comment by jmirabel** [comment]
> We can also exclude these reformating commits from git blame, with `--ignore-rev` / `--ignore-revs-file`. A `.git-blame-ignore-revs` file, which can be versioned in the repo, seems to a common convention: https://www.moxio.com/blog/43/ignoring-bulk-change-commits-with-git-blame / https://akrabat.com/ignoring-revisions-with-git-blame/

Didn't know about this. Indeed, that makes code reformatting a lot more attractive !

**Comment by nim65s** [comment]
Then I suggest we merge this, and release. Should I handle that ?

**Comment by jmirabel** [comment]
Don't you want to add the git blame file first ?
Then, yes, it's good for me.

**Comment by nim65s** [comment]
sure

**Comment by nim65s** [comment]
PS: Github support for this feature is still in beta: https://github.com/github/feedback/discussions/5033

**Comment by wxmerkt** [comment]
Should we expand the README on how to use pre-commit and to manually set the git-blame setting (per commit message it needs to be set manually on every developer machine)?
```
[add git blame ignore file](https://github.com/humanoid-path-planner/hpp-fcl/pull/280/commits/5fea4840a47ec1b895757f6ecc5bdc691ae1535a)
[5fea484](https://github.com/humanoid-path-planner/hpp-fcl/pull/280/commits/5fea4840a47ec1b895757f6ecc5bdc691ae1535a)

To use it, either:
- git blame --ignore-revs-file .git-blame-ignore-revs
- git config blame.ignoreRevsFile .git-blame-ignore-revs
```

**Comment by nim65s** [comment]
I'm not sure how useful it would be to add more docs about those standard tools here. 

They are becoming pretty common, and for anybody who is not aware of those, github UI will automatically provide the right blame, and pre-commit.ci will automatically add commits to re-format if needed. 

But I won't oppose if someone provide that doc :)

**Comment by jcarpent** [comment]
I can handle the release soon also.

**Comment by jcarpent** [comment]
Before doing the new release, I will fix this issue #267.

**Comment by jcarpent** [comment]
The new release version will thus be 2.0.0

**Pull request merged**
